service: myServerlessProject

provider:
    name: aws
    runtime: nodejs20.x
    profile: typescript-node
    region: ap-south-1
    stage: dev
    environment:
        DB_CONNECION: mongodb://localhost:27017

package:
    individually: true

functions:
    hello:
        handler: handler.hello
        events:
          - http: ANY /{proxy+}
          - http: ANY /
            
   
   
                      